<?php

namespace AppBundle\Repository;

/**
 * WeatherStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherStationRepository extends \Doctrine\ORM\EntityRepository
{
}
