<?php

namespace AppBundle\Repository;

/**
 * WeatherStationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherStationDataRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLatestWeatherDataForPin($pin) {
        return $this->createQueryBuilder('wdata')
            ->innerJoin('wdata.weatherStation', 'wstation')
            ->where('wstation.id = :pin')
            ->setParameter('pin', $pin)
            ->orderBy('wdata.updateTime', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
