app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix: /api