app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app_user_homepage:
    path:     /userhome
    defaults: { _controller: AppBundle:Home:indexUser }

app_proposition:
    path:     /proposition
    defaults: { _controller: AppBundle:Document:proposition }

app_acquisition_connaissances:
    path:     /acquisition_connaissances
    defaults: { _controller: AppBundle:Document:acquisitionConnaissances }

app_demarche_experimentale:
    path:     /demarche_experimentale
    defaults: { _controller: AppBundle:Document:demarcheExperimentale }

app_difficultes:
    path:     /difficultes
    defaults: { _controller: AppBundle:Document:difficultes }

app_resultats_recherche:
    path:     /resultats_recherche
    defaults: { _controller: AppBundle:Document:resultatsRecherche }

app_conclusion_bilan:
    path:     /conclusion_bilan
    defaults: { _controller: AppBundle:Document:conclusionBilan }

app_bibliographie:
    path:     /bibliographie
    defaults: { _controller: AppBundle:Document:bibliographie }